[package]
name = "lambda-calculus-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
lambda-calculus = { path = "../lambda-calculus" }
proc-macro2 = "1.0"
quote = "1.0"
